/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Contract No]
      ,[Reference Contract Number]
      ,[From Date]
      ,[End Date]
      ,[Current Date]
      ,[Contract Term (in Month)]
      ,[Contract Start to Date ]
      ,[Outlet Code]
      ,[Outlet Name]
      ,[Sales Representative]
      ,[Sales Supervisor]
      ,[SOM]
      ,[Outlet Group Code]
      ,[Status]
      ,[Distributor Code]
      ,[Sync_ to All Agent]
      ,[Item Code]
      ,[Unit of Measure]
      ,[Conversion HL]
      ,[Expected Vol. (Ctn/Keg)]
      ,[Expected Vol. (HL)]
      ,[Expect AMS (HL)]
      ,[Accumulate Expected Vol. (HL) Contract Start to Date]
      ,[Actual AMS (HL)]
      ,[Accumulated Actual Vol. (HL) Contract Start to Date]
      ,[In the Month Vol.HL]
      ,[Accumulated Vol. Variance]
      ,[# of Month behind]
      ,[Total Gratis Carton]
      ,[Total Gratis HL]
      ,[Price without VAT (HL)]
      ,[Amount Gratis HL]
      ,[Gratis by vol (USD)]
      ,[FOC Offer (USD)]
      ,[Tier Incentive (USD)]
      ,[POSM (USD)]
      ,[Cash Offer ( USD)]
      ,[OutletNameEn]
      ,[Channel_Name]
      ,[Channel Head]
      ,[Ranks]
      ,[Business_Segment]
      ,[Segment]
      ,[SALES_REP_CODE]
      ,[SALES_REP_NAME]
      ,[level1_territory_Internal_Email]
      ,[level1_territory_Internal_DomainName]
      ,[SUPERVISOR_ID]
      ,[SUPERVISOR_NAME]
      ,[level2_territory_Internal_Email]
      ,[level2_territory_Internal_DomainName]
      ,[SOMID]
      ,[SOMName]
      ,[level3_territory_Internal_Email]
      ,[level3_territory_Internal_DomainName]
      ,[CHID]
      ,[CHName]
      ,[level4_territory_Internal_Email]
      ,[level4_territory_Internal_DomainName]
      ,[level1_territory and Name]
      ,[level2_territory and Name]
      ,[level3_territory and Name]
      ,[level4_territory and Name]
      ,[ItemDesc]
      ,[itm_convert]
      ,[Price]
      ,[Actual AMS (CTN)]
      ,[Actual AMS (USD)]
      ,[Expected Vol. (USD)]
      ,[Expect AMS (USD)]
  FROM [DIS].[dbo].[Tracking Sales Volume Target outlet sponsorship_Modify]