/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [DocumentNo_]
      ,[DepoCode]
      ,[Sell-to Customer No_]
      ,[Sell-to Customer Name]
      ,[OutletCreditStatus]
      ,[Sell-to Address]
      ,[Order Date]
      ,[Posting Date]
      ,[Shipment Date]
      ,[Posting Description]
      ,[Due Date]
      ,[Document Date]
      ,[years]
      ,[months]
      ,[dates]
      ,[monthsname]
      ,[yearMonth]
      ,[weekNumber]
      ,[YearMonthSort]
      ,[External Document No_]
      ,[Pre-Assigned No_ Series]
      ,[No_ Series]
      ,[Order No_ Series]
      ,[Pre-Assigned No_]
      ,[Acknowledgement Gratis]
      ,[Invoice Remarks]
      ,[CBL Doc_ Type]
      ,[DocType]
      ,[OrderType]
      ,[Document No_]
      ,[Line No_]
      ,[Type]
      ,[ItemCode]
      ,[Location Code]
      ,[Quantity]
      ,[HL]
      ,[Unit Price]
      ,[Unit Cost (LCY)]
      ,[VAT _]
      ,[Line Discount _]
      ,[Line Discount Amount_System]
      ,[amount1]
      ,[Amount Including VAT]
      ,[Allow Invoice Disc_]
      ,[Units per Parcel]
      ,[VAT Base Amount]
      ,[Unit Cost]
      ,[Line Amount]
      ,[Quantity (Base)]
      ,[Sponsor Qty]
      ,[Brand]
      ,[itm_code]
      ,[itm_mt_code]
      ,[itm_des]
      ,[itm_mou]
      ,[itm_convert]
      ,[itm_vol]
      ,[itm_brand]
      ,[itm_pack_type]
      ,[itm_pack]
      ,[itm_type]
      ,[itm_pallet]
      ,[itm_target_group]
      ,[itm_pro_type]
      ,[itm_prom_type]
      ,[itm_prom_type_sc]
      ,[Itm_Group]
      ,[Price]
      ,[Cost]
      ,[Commission]
      ,[Posted Invoice No_]
      ,[Reason Code]
      ,[Reason Description]
      ,[Sales Rep]
      ,[Sales Sup]
      ,[OutletCode]
      ,[OutletNameKh]
      ,[OutletNameEn]
      ,[AddressKh1]
      ,[AddressKh2]
      ,[CityKh]
      ,[Phone No_]
      ,[Budgeted Amount]
      ,[Amount]
      ,[Blocked]
      ,[Invoice Copies]
      ,[Last Statement No_]
      ,[Print Statements]
      ,[Priority]
      ,[Bill-to Customer No_]
      ,[Prepayment _]
      ,[Shipping Time]
      ,[Shipping Agent Service Code]
      ,[Allow Line Disc_]
      ,[AddressEn1]
      ,[AddressEn2]
      ,[Code]
      ,[Name]
      ,[Area]
      ,[Abb]
      ,[Mail]
      ,[Region]
      ,[OutletName]
      ,[Province]
      ,[Account_Type]
      ,[Segment]
      ,[ChannelName]
      ,[OutletAddress]
      ,[Ranks]
      ,[Category]
      ,[OutletOwnerName]
      ,[OwnerPhoneNum]
      ,[QutleTypeRemark]
      ,[TradeTypeName]
      ,[OutletType]
      ,[ContractType]
      ,[OrderCategory]
      ,[BrandTitle]
      ,[RingPullType]
      ,[RSLSATeam]
      ,[AgentEmail]
      ,[Integrate SO]
      ,[B2B Order No_]
      ,[Shipment Number]
      ,[ST Number]
      ,[OT Number]
      ,[Wedding/Function Type]
      ,[Wedding/Function SubType Code]
      ,[Wedding/Function Type Description]
      ,[Wedding/Function Code]
      ,[Consumer Name #1]
      ,[Consumer Name #2]
      ,[Consumer Phone Number #1]
      ,[Wedding/Function Address]
      ,[Contractor Code]
      ,[Contractor Name]
      ,[Referral Code]
      ,[Wedding/Function Date]
      ,[Createby]
      ,[Contract Type1]
      ,[Contract Type]
      ,[Invoice Type]
      ,[Line Type]
      ,[Proceed Time]
      ,[Prices Including VAT]
      ,[Unit Price Ex.VAT]
      ,[Line Discount Amount]
      ,[level1_territory]
      ,[level1_territory_name]
      ,[level1_territory_Internal_Email]
      ,[level1_territory_Internal_DomainName]
      ,[level2_territory]
      ,[level2_territory_name]
      ,[level2_territory_Internal_Email]
      ,[level2_territory_Internal_DomainName]
      ,[level3_territory]
      ,[level3_territory_name]
      ,[level3_territory_Internal_Email]
      ,[level3_territory_Internal_DomainName]
      ,[level4_territory]
      ,[level4_territory_name]
      ,[level4_territory_Internal_Email]
      ,[level4_territory_Internal_DomainName]
      ,[level1_territory and Name]
      ,[level2_territory and Name]
      ,[level3_territory and Name]
      ,[level4_territory and Name]
      ,[City]
      ,[District]
      ,[Commune]
      ,[Village]
  FROM [DWH_HCAM].[dbo].[V_F_DIS_BI]
